bookflood/urls.py
from django.contrib import admin
from django.urls import path
from bookflood import views

urlpatterns = [
    path('', views.home, name='home'),
    path('person', views.view_person, name='person'),
    path('books', views.BookList.as_view(), name='books'),
    path('books/add', views.BookCreate.as_view(), name='add_book'),
    path('books/<pk>', views.BookDetail.as_view(), name='book_detail')
]

django_bookflood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookflood.urls')),
]

bookflood/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Country(models.Model):
	name=models.CharField(max_length=100)

	class Meta(object):
		verbose_name_plural='countries'

	def __str__(self):
		return self.name

class Genre(models.Model):
	name=models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Language(models.Model):
	name=models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Book(models.Model):
	title=models.CharField(max_length=255)
	author=models.CharField(max_length=255)
	genre=models.ForeignKey(Genre, on_delete=models.CASCADE)
	isbn=models.IntegerField(blank=True, null=True)
	price=models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True) 
	date_published=models.DateField(blank=True, null=True)
	language=models.ForeignKey(Language, on_delete=models.CASCADE)

	def __str__(self): 
		return self.title

	def get_absolute_url(self):
		return reverse('book_detail', kwargs={'pk':self.id})

class UserProfile(models.Model):
	date_of_birth=models.DateField()
	country=models.ForeignKey(Country, on_delete=models.CASCADE)
	books_read=models.ManyToManyField(Book, related_name='read_it')
	books_wanted=models.ManyToManyField(Book, related_name='want_it')
	favorite_genres=models.ManyToManyField(Genre)
	languages=models.ManyToManyField(Language)
	user=models.OneToOneField(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.user.first_name

bookflood/views.py
from django.shortcuts import render
from django.views.generic import View, DetailView, ListView
from django.views.generic.edit import CreateView
from bookflood.models import UserProfile, Book 

class BookView(View):
	model=Book

class BookList(BookView, ListView):
	template_name='book.html'

class BookDetail(BookView, DetailView):
	pass

class BookCreate(BookView, CreateView):
	fields=['title', 'author', 'genre', 'isbn', 'language']

def home(request):
	userprofiles=UserProfile.objects.all()
	data={'people':userprofiles}
	return render(request, 'home.html', data)

def view_person(request):
	person=UserProfile.objects.all()
	data={'person':person}
	return render(request, 'person.html', data)

bookflood/templates/base.html
 <!DOCTYPE html>
<html>
{% load staticfiles %}
	<head>
		<title>Books</title>
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		  <link rel="stylesheet" href="{% static 'css/bookflood.css' %}">
	</head>
	<body>
		<div>
			<h3><a href="{% url 'home' %}">Home</a></h3>
			<h3><a href="{% url 'books' %}">All Books</a></h3>	
		</div>
		{% block content %} 
		{% endblock %}
	</body>
</html>

bookflood/templates/book.html
{% extends 'base.html' %}
{% block content %}
{% for b in book_list %}
	<div>
		<a href="{%url 'book_detail' pk=b.id%}"> {{ b }}</a>
	</div>
	{% endfor %}
	<a href="{%url 'add_book' %}"> Add Book</a>
{% endblock %}

bookflood/templates/bookflood/book_detail.html
 <!DOCTYPE html>
<html>
{% load staticfiles %}
	<head>
		<title>Books</title>
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		  <link rel="stylesheet" href="{% static 'css/bookflood.css' %}">
	</head>
	<body>
		<div>
			<h1><a href="">Books</a></h1>
			<h3><a href="{% url 'books' %}">All Books</a></h3>	
		</div>
		{{book.title}}
		<br></body>
		{{book.author}}
		<br></body>
		{{book.genre}}
		<br></body>
		{{book.isbn}}
		<br></body>
		{{book.language}}
	</body>
</html>

bookflood/templates/bookflood/book_form.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="POST">
	{%csrf_token%}
	{{form.as_p}}
	<input type="Submit">
</form>

{% endblock %}

bookflood/templates/home.html
<html>
<body>
	<h1> Welcome to Bookflood! </h1>
	{% for p in people %}
	{{ p }}
	{% endfor %}
</body>
</html>

bookflood/templates/person.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
	<head>
		<title>User Profile</title>
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		  <link rel="stylesheet" href="{% static 'css/bookflood.css' %}">
	</head>
	<body>
		<div>
			<h1><a href="">This is an information page about a person.</a></h1>
			<h3><a href="{% url 'home' %}">Home</a></h3>	
		</div>
			
		{% for p in person %}
			<div>
				{{ p }}
			</div>
		{% endfor %}
	</body>
</html>